kind: pipeline
type: docker
name: sync-stage

trigger:
  branch:
    - UC-999-init
  event:
    - push

steps:
  - name: sync-to-stage
    image: node:22
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_REGION:
        from_secret: aws_region
    commands:
      - npm install
      - npx tsx sync.ts --bucket university-renderlearn-llm-content-stage

---

kind: pipeline
type: docker
name: sync-prod

trigger:
  branch:
    - production
  event:
    - push

steps:
  - name: sync-to-prod
    image: node:22
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_REGION:
        from_secret: aws_region
    commands:
      - npm install
      - npx tsx sync.ts --bucket university-renderlearn-llm-content-prod
